AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3JarFileName:
    Type: String
    Default: aws-kinesis-analytics-java-apps-1.0.jar
  ShardCount:
    Type: Number
    Default: 2
    MaxValue: 200
    MinValue: 1
  RetentionHours:
    Type: Number
    Default: 24
    MaxValue: 8760
    MinValue: 24
  EnableEnhancedMonitoring:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  ProducerVpcId:
    Type: 'AWS::EC2::VPC::Id'
  ProducerSubnetId:
    Type: 'AWS::EC2::Subnet::Id'
  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
      - DEBUG
      - ERROR
      - INFO
      - WARN
  MetricsLevel:
    Type: String
    Default: TASK
    AllowedValues:
      - APPLICATION
      - OPERATOR
      - PARALLELISM
      - TASK
 
Resources:
  KdsInputdatasstream:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      Name: KdsInputdatasstream
      ShardCount:
        Ref: ShardCount
      RetentionPeriodHours:
        Ref: RetentionHours
  
  KdaApplicationforsiteiq:
    Type: 'AWS::KinesisAnalyticsV2::Application'
    Properties:
      RuntimeEnvironment: FLINK-1_11
      ServiceExecutionRole:
        'Fn::GetAtt':
          - KdaAppRoleforsiteiq
          - Arn
      ApplicationConfiguration:
        ApplicationCodeConfiguration:
          CodeContent:
            S3ContentLocation:
              BucketARN:
                'Fn::Join':
                  - ''
                  - - 'arn:'
                    - Ref: 'AWS::Partition'
                    - ':s3:::solutions-'
                    - Ref: 'AWS::Region'
              FileKey: !Ref S3JarFileName
          CodeContentType: ZIPFILE
       
        EnvironmentProperties:
          PropertyGroups:
            - PropertyGroupId: FlinkApplicationProperties
              PropertyMap:
                InputStreamName:
                  Ref: KdsInputdatasstream
                OutputBucketName:
                  Ref: OutputBucketB1E245A7
        FlinkApplicationConfiguration:
          CheckpointConfiguration:
            ConfigurationType: DEFAULT
          MonitoringConfiguration:
            ConfigurationType: CUSTOM
            LogLevel:
              Ref: LogLevel
            MetricsLevel:
              Ref: MetricsLevel
          ParallelismConfiguration:
            ConfigurationType: CUSTOM
  KdaApplicationroleandpolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'kinesis:DescribeStreamSummary'
              - 'kinesis:GetRecords'
              - 'kinesis:GetShardIterator'
              - 'kinesis:ListShards'
              - 'kinesis:SubscribeToShard'
            Effect: Allow
            Resource:
              'Fn::GetAtt':
                - KdsInputdatasstream
                - Arn
          - Action:
              - 's3:GetObject*'
              - 's3:GetBucket*'
              - 's3:List*'
              - 's3:DeleteObject*'
              - 's3:PutObject*'
              - 's3:Abort*'
            Effect: Allow
            Resource:
              - 'Fn::GetAtt':
                  - OutputBucketB1E245A7
                  - Arn
              - 'Fn::Join':
                  - ''
                  - - 'Fn::GetAtt':
                        - OutputBucketB1E245A7
                        - Arn
                    - /*
        Version: 2012-10-17
      PolicyName:  KdaApplicationroleandpolicy
      Roles:
        - Ref:  KdaAppRoleforsiteiq
  KdaAppRoleforsiteiq:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: kinesisanalytics.amazonaws.com
        Version: 2012-10-17
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - 's3:GetObjectVersion'
                  - 's3:GetObject'
                Effect: Allow
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:'
                      - Ref: 'AWS::Partition'
                      - ':s3:::solutions-'
                      - Ref: 'AWS::Region'
                      - >-
                        /aws-streaming-data-solution-for-amazon-kinesis/v1.5.0/kda-flink-demo.zip
            Version: 2012-10-17
          PolicyName: S3Policy
        - PolicyDocument:
            Statement:
              - Action: 'logs:DescribeLogGroups'
                Effect: Allow
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:'
                      - Ref: 'AWS::Partition'
                      - ':logs:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - Ref: 'AWS::AccountId'
                      - ':log-group:*'
              - Action:
                  - 'logs:DescribeLogStreams'
                  - 'logs:PutLogEvents'
                Effect: Allow
                Resource:
                  'Fn::GetAtt':
                    - KdaLogGroups
                    - Arn
            Version: 2012-10-17
          PolicyName: LogsPolicy
        - PolicyDocument:
            Statement:
              - Action:
                  - 'ec2:CreateNetworkInterface'
                  - 'ec2:DescribeNetworkInterfaces'
                  - 'ec2:DescribeVpcs'
                  - 'ec2:DeleteNetworkInterface'
                  - 'ec2:DescribeDhcpOptions'
                  - 'ec2:DescribeSubnets'
                  - 'ec2:DescribeSecurityGroups'
                Effect: Allow
                Resource: '*'
              - Action: 'ec2:CreateNetworkInterfacePermission'
                Effect: Allow
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'arn:'
                      - Ref: 'AWS::Partition'
                      - ':ec2:'
                      - Ref: 'AWS::Region'
                      - ':'
                      - ':network-interface/*'
            Version: 2012-10-17
          PolicyName: VpcPolicy
  KdaLoggingEAF1BAAE:
    Type: 'AWS::KinesisAnalyticsV2::ApplicationCloudWatchLoggingOption'
    Properties:
      ApplicationName: 
        Ref: KdaApplicationforsiteiq
      CloudWatchLoggingOption:
        LogStreamARN:
          'Fn::Join':
            - ''
            - - 'arn:'
              - Ref: 'AWS::Partition'
              - ':logs:'
              - Ref: 'AWS::Region'
              - ':'
              - Ref: 'AWS::AccountId'
              - ':log-group:'
              - Ref: KdaLogGroups
              - ':log-stream:'
              - Ref: KdaLogStreams
  KdaLogGroups:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      RetentionInDays: 365
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  KdaLogStreams:
    Type: 'AWS::Logs::LogStream'
    Properties:
      LogGroupName:
        Ref: KdaLogGroups
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  OutputAccessLogsBucket8BE3FC5F:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: LogDeliveryWrite
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  OutputBucketB1E245A7:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Id: multipart-upload-rule
            Status: Enabled
          - Id: intelligent-tiering-rule
            Status: Enabled
            Transitions:
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 1
      LoggingConfiguration:
        DestinationBucketName:
          Ref: OutputAccessLogsBucket8BE3FC5F
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  OutputBucketPolicyD67A70DF:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket:
        Ref: OutputBucketB1E245A7
      PolicyDocument:
        Statement:
          - Action: '*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
            Effect: Deny
            Principal: '*'
            Resource:
              - 'Fn::Join':
                  - ''
                  - - 'Fn::GetAtt':
                        - OutputBucketB1E245A7
                        - Arn
                    - /*
              - 'Fn::GetAtt':
                  - OutputBucketB1E245A7
                  - Arn
            Sid: HttpsOnly
        Version: 2012-10-17
		

